#!/bin/sh
ssh root@159.223.58.234 << 'EOF'
    cd ~/backend-jenkins-test
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install 16.8.0	//젠킨스에서 설정한 node 버전
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF